-- =============================================================================
-- seed.sql — GENERATED by app/scripts/build-seed.mjs. Do not edit by hand.
--
-- Source: Job_list_10th_Sept_3.docx (40 lines, verbatim in
-- scripts/source_lines.json). Every row keeps its source_text.
--
-- Nothing here is inferred. Where the document is silent the column is NULL
-- and the row carries needs_review = TRUE. See database/SEED_REVIEW.md for
-- all 76 flags.
--
-- Year assumption: dates in the source omit the year except one. 2026 is
-- taken from line 8 ("Mother & child camp campaign: Vivek 26th Sept 2026") — the only line stating a year.
-- =============================================================================

BEGIN;

-- --- People named in the source ------------------------------------------
-- These are people work is ATTRIBUTED to, not login accounts. Nothing is
-- written to auth.users: that table belongs to Supabase's auth service, rows
-- inserted by hand lack the columns GoTrue requires and cannot sign in, and
-- its email index is PARTIAL so ON CONFLICT (email) fails with 42P10.
--
-- When one of these people is given a login, create them through
-- Authentication -> Users and relink. The @placeholder.invalid addresses
-- guarantee no collision with a real sign-up in the meantime.

INSERT INTO public.users (email, full_name)
VALUES ('akshay@placeholder.invalid', 'Akshay')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('anshika@placeholder.invalid', 'Anshika')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('atampreet@placeholder.invalid', 'Atampreet')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('dr..tarang@placeholder.invalid', 'Dr. Tarang')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('himanshu@placeholder.invalid', 'Himanshu')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('jaggi@placeholder.invalid', 'Jaggi')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('love@placeholder.invalid', 'Love')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('mudit@placeholder.invalid', 'Mudit')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nasir@placeholder.invalid', 'Nasir')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nirmal@placeholder.invalid', 'Nirmal')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nishith@placeholder.invalid', 'Nishith')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('parul@placeholder.invalid', 'Parul')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('shreyak@placeholder.invalid', 'Shreyak')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('sushant@placeholder.invalid', 'Sushant')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vidisha@placeholder.invalid', 'Vidisha')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vijaya@placeholder.invalid', 'Vijaya')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vivek@placeholder.invalid', 'Vivek')
ON CONFLICT (email) DO NOTHING;

-- --- Role assignments ------------------------------------------------------
-- NOTE: the source document states NO roles for anyone. These assignments are
-- an ASSUMPTION carried over so RLS is exercisable, flagged as such in the
-- review file. Correct them in the admin UI; nothing in the engine depends on
-- a specific person holding a specific role.
INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, r.id FROM public.users u CROSS JOIN public.roles r
WHERE u.email LIKE '%@placeholder.invalid' AND r.name = 'CREATOR'
ON CONFLICT DO NOTHING;


-- --- Workflow -------------------------------------------------------------
-- A single permissive template so imported rows have somewhere to sit. The
-- real stage list is the 11-stage flow; it is NOT generated here because the
-- source document does not say which stage any item is at.
INSERT INTO public.workflow_templates (name, description, multi_owner_behavior, is_default)
VALUES ('Imported (unclassified)',
        'Holding workflow for rows imported from the 10th Sept job list.',
        'COLLABORATIVE', FALSE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.workflow_stages (workflow_id, name, stage_order, requires_approval)
SELECT w.id, v.name, v.ord, v.appr
FROM public.workflow_templates w,
     (VALUES ('IMPORTED', 1, FALSE), ('APPROVAL', 2, TRUE), ('DONE', 3, FALSE))
       AS v(name, ord, appr)
WHERE w.name = 'Imported (unclassified)'
ON CONFLICT (workflow_id, name) DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'SUBMISSION'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='IMPORTED'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='APPROVAL'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'APPROVED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='DONE'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'CHANGES_REQUIRED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='IMPORTED'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;


-- --- Jobs and work items -----------------------------------------------------
-- Retired: see EMIT_JOB_LIST_IMPORT at the top of build-seed.mjs and
-- 0030_soft_delete_imported_job_list.sql. This script still parses the
-- source document (so the people list below is still derived from it), it
-- just no longer emits jobs/work_items rows.

COMMIT;
