-- =============================================================================
-- seed.sql — GENERATED by scripts/build-seed.mjs. Do not edit by hand.
--
-- Source: Job_list_10th_Sept_3.docx (40 lines, verbatim in
-- scripts/source_lines.json). Every row keeps its source_text.
--
-- Nothing here is inferred. Where the document is silent the column is NULL
-- and the row carries needs_review = TRUE. See database/SEED_REVIEW.md for
-- all 76 flags.
--
-- Year assumption: dates in the source omit the year except one. 2026 is
-- taken from line 8 ("Mother & child camp campaign: Vivek 26th Sept 2026") — the only line stating a year.
-- =============================================================================

BEGIN;

-- --- People named in the source ------------------------------------------
-- These are people work is ATTRIBUTED to, not login accounts. Nothing is
-- written to auth.users: that table belongs to Supabase's auth service, rows
-- inserted by hand lack the columns GoTrue requires and cannot sign in, and
-- its email index is PARTIAL so ON CONFLICT (email) fails with 42P10.
--
-- When one of these people is given a login, create them through
-- Authentication -> Users and relink. The @placeholder.invalid addresses
-- guarantee no collision with a real sign-up in the meantime.

INSERT INTO public.users (email, full_name)
VALUES ('akshay@placeholder.invalid', 'Akshay')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('anshika@placeholder.invalid', 'Anshika')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('atampreet@placeholder.invalid', 'Atampreet')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('dr..tarang@placeholder.invalid', 'Dr. Tarang')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('himanshu@placeholder.invalid', 'Himanshu')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('jaggi@placeholder.invalid', 'Jaggi')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('love@placeholder.invalid', 'Love')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('mudit@placeholder.invalid', 'Mudit')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nasir@placeholder.invalid', 'Nasir')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nirmal@placeholder.invalid', 'Nirmal')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('nishith@placeholder.invalid', 'Nishith')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('parul@placeholder.invalid', 'Parul')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('shreyak@placeholder.invalid', 'Shreyak')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('sushant@placeholder.invalid', 'Sushant')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vidisha@placeholder.invalid', 'Vidisha')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vijaya@placeholder.invalid', 'Vijaya')
ON CONFLICT (email) DO NOTHING;
INSERT INTO public.users (email, full_name)
VALUES ('vivek@placeholder.invalid', 'Vivek')
ON CONFLICT (email) DO NOTHING;

-- --- Role assignments ------------------------------------------------------
-- NOTE: the source document states NO roles for anyone. These assignments are
-- an ASSUMPTION carried over so RLS is exercisable, flagged as such in the
-- review file. Correct them in the admin UI; nothing in the engine depends on
-- a specific person holding a specific role.
INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, r.id FROM public.users u CROSS JOIN public.roles r
WHERE u.email LIKE '%@placeholder.invalid' AND r.name = 'CREATOR'
ON CONFLICT DO NOTHING;


-- --- Workflow -------------------------------------------------------------
-- A single permissive template so imported rows have somewhere to sit. The
-- real stage list is the 11-stage flow; it is NOT generated here because the
-- source document does not say which stage any item is at.
INSERT INTO public.workflow_templates (name, description, multi_owner_behavior, is_default)
VALUES ('Imported (unclassified)',
        'Holding workflow for rows imported from the 10th Sept job list.',
        'COLLABORATIVE', FALSE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.workflow_stages (workflow_id, name, stage_order, requires_approval)
SELECT w.id, v.name, v.ord, v.appr
FROM public.workflow_templates w,
     (VALUES ('IMPORTED', 1, FALSE), ('APPROVAL', 2, TRUE), ('DONE', 3, FALSE))
       AS v(name, ord, appr)
WHERE w.name = 'Imported (unclassified)'
ON CONFLICT (workflow_id, name) DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'SUBMISSION'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='IMPORTED'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='APPROVAL'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'APPROVED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='DONE'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'CHANGES_REQUIRED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='IMPORTED'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;


-- --- Jobs and work items ---------------------------------------------------

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Cardiac : 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:0')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:0'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Love' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'newspaper ad: hindi & English : Love - closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'newspaper ad: hindi & English : Love - closed',
       'joblist:item:1'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:1' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:0'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nasir' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Whatsapp : Nasir Closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Whatsapp : Nasir Closed',
       'joblist:item:2'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:2' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:0'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Love' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Emailer : Love - closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Emailer : Love - closed',
       'joblist:item:3'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:3' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:0'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Love' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Flyer : Love -',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | NO_STATUS: Line reads "Flyer : Love - " with a trailing dash and nothing after it. Owner is Love; status genuinely absent.',
       'Flyer : Love -',
       'joblist:item:4'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:4' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:0'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nasir' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Meta Ad : Closed Nasir',
       'COMPLETED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Meta Ad : Closed Nasir',
       'joblist:item:5'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:5' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Sales emailer Neuro Fast: love & shreyak : 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:6')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:6'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sales emailer Neuro Fast: love & shreyak : 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Love, Shreyak — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Sales emailer Neuro Fast: love & shreyak : 10th Sept',
       'joblist:item:6'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:6' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:6' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('ShardaCare hai na film: anshika : 10th sept by 11 am', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:7')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:7'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Anshika' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'ShardaCare hai na film: anshika : 10th sept by 11 am',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'ShardaCare hai na film: anshika : 10th sept by 11 am',
       'joblist:item:7'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:7' AND u.full_name = 'Anshika'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Mother & child camp campaign: Vivek 26th Sept 2026', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:8')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:8'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'newspaper ad',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'newspaper ad',
       'joblist:item:9'
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:8'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Whatsapp',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Whatsapp',
       'joblist:item:10'
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:8'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Emailer',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Emailer',
       'joblist:item:11'
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:8'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Flyer',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Flyer',
       'joblist:item:12'
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:8'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'P1 Meta creative – 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'P1 Meta creative – 10th Sept',
       'joblist:item:13'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:14')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:14'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept',
       'NOT_STARTED',
       '2026-09-09',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Himanshu, Dr. Tarang — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | ROLE_AMBIGUOUS: Is "Dr. Tarang" the requester/stakeholder or an owner? The line reads "Dr. Tarang: discuss the requirement" then names Himanshu as doing the video. Recorded as a mention only — no ownership assigned.',
       'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept',
       'joblist:item:14'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:14' AND u.full_name = 'Himanshu'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:14' AND u.full_name = 'Dr. Tarang'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Lab images – Himanshu Vidisha – 10th sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:15')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:15'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Lab images – Himanshu Vidisha – 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Himanshu, Vidisha — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Lab images – Himanshu Vidisha – 10th sept',
       'joblist:item:15'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:15' AND u.full_name = 'Himanshu'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:15' AND u.full_name = 'Vidisha'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Physio requirements: read document : Jaggi & Vijaya', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:16')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:16'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Physio requirements: read document : Jaggi & Vijaya',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Jaggi, Vijaya — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Physio requirements: read document : Jaggi & Vijaya',
       'joblist:item:16'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:16' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:16' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('World heart day newspaper ad (half advertorial half ad) content - Vijaya', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:17')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:17'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Vijaya' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'World heart day newspaper ad (half advertorial half ad) content - Vijaya',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'World heart day newspaper ad (half advertorial half ad) content - Vijaya',
       'joblist:item:17'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:17' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:18')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:18'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Shreyak, Nirmal, Mudit — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept',
       'joblist:item:18'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:18' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:18' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:18' AND u.full_name = 'Mudit'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:19')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:19'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Atampreet' LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing',
       'PENDING',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Vijaya, Atampreet — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | ROLE_AMBIGUOUS: "get it approved by atampreet" makes Atampreet the APPROVER, not the owner. "Vijaya for makerchecker" is a second, different review role. The line also ends "sent for printing", implying it already passed both. Sequence not reconstructible from the source. | UNPARSED_TERM: "total solutions" — unclear whether a vendor name, a deliverable, or part of the booklet title.',
       'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing',
       'joblist:item:19'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:19' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:19' AND u.full_name = 'Atampreet'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:20')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:20'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Akshay' LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)',
       'PENDING',
       '2026-09-08',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'MULTIPLE_PEOPLE: Vivek, Vijaya, Akshay — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)',
       'joblist:item:20'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:20' AND u.full_name = 'Vivek'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:20' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:20' AND u.full_name = 'Akshay'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:21')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:21'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS',
       'PENDING',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Nasir, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | UNRESOLVED_RECIPIENT: Cannot resolve "ms" to a person | UNRESOLVED_RECIPIENT: "MS" is an unresolved initialism (Medical Superintendent?). Not added to the roster; recorded verbatim.',
       'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS',
       'joblist:item:21'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:21' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:21' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('PIL IUI: Jaggi : 12th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:22')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:22'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Jaggi' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'PIL IUI: Jaggi : 12th Sept',
       'NOT_STARTED',
       '2026-09-12',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'PIL IUI: Jaggi : 12th Sept',
       'joblist:item:22'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:22' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:23')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:23'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Jaggi' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed',
       'COMPLETED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       FALSE,
       NULL,
       'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed',
       'joblist:item:23'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:23' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:24')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:24'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Parul' LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th',
       'PENDING',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Jaggi, Parul — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | PENDING_WITH_NAMED: Source says "approval pending" AND names Parul. Per your instruction the named person wins, so pending_with = Parul rather than the literal "unknown".',
       'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th',
       'joblist:item:24'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:24' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:24' AND u.full_name = 'Parul'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Green belt design approval and costing : costing sent to purchase 9th Sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:25')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:25'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Green belt design approval and costing : costing sent to purchase 9th Sept',
       'PENDING',
       '2026-09-09',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_OWNER: No owner named anywhere on this line; owner left NULL | UNRESOLVED_RECIPIENT: Cannot resolve "purchase 9th sept" to a person',
       'Green belt design approval and costing : costing sent to purchase 9th Sept',
       'joblist:item:25'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Roundabout creatives: flagpoles: Jaggi:  10th sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:26')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:26'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Jaggi' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Roundabout creatives: flagpoles: Jaggi:  10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Roundabout creatives: flagpoles: Jaggi:  10th sept',
       'joblist:item:26'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:26' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('YK sir Grandson video : Anshika & Vidisha – 9th sept closed10', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:27')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:27'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10',
       'COMPLETED',
       '2026-09-09',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'MULTIPLE_PEOPLE: Anshika, Vidisha — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | SOURCE_ARTEFACT: Line ends "closed10" — the trailing "10" appears to be a stray list number, not part of the status. Read as "closed"; the "10" is discarded but preserved in source_text.',
       'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10',
       'joblist:item:27'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:27' AND u.full_name = 'Anshika'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:27' AND u.full_name = 'Vidisha'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:28')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:28'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Nasir, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept',
       'joblist:item:28'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:28' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:28' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Printing Collateral Ayushman Event – Nasir : closed', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:29')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:29'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nasir' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Printing Collateral Ayushman Event – Nasir : closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Printing Collateral Ayushman Event – Nasir : closed',
       'joblist:item:29'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:29' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr. Lipi Clinic branding – Nirmal – vendor aligned', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:30')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:30'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nirmal' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Lipi Clinic branding – Nirmal – vendor aligned',
       'IN_PROGRESS',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Dr. Lipi Clinic branding – Nirmal – vendor aligned',
       'joblist:item:30'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:30' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:31')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:31'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nirmal' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept',
       'joblist:item:31'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:31' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr Avinash clinic branding – 10th sept Shreyak', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:32')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:32'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Shreyak' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr Avinash clinic branding – 10th sept Shreyak',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Dr Avinash clinic branding – 10th sept Shreyak',
       'joblist:item:32'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:32' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:33')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:33'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Nirmal' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)',
       'PENDING',
       '2026-09-11',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'DATE_MEANING: "vendor aligned for 11th sept" — the 11th Sept refers to the vendor visit, not necessarily the work deadline. Recorded as deadline with this caveat.',
       'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)',
       'joblist:item:33'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:33' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dibrugarh Flyer - Vivek', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:34')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:34'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Vivek' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dibrugarh Flyer - Vivek',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Dibrugarh Flyer - Vivek',
       'joblist:item:34'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:34' AND u.full_name = 'Vivek'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Outstation Hoarding  - Sushant', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:35')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:35'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Sushant' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Outstation Hoarding  - Sushant',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Outstation Hoarding  - Sushant',
       'joblist:item:35'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:35' AND u.full_name = 'Sushant'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('PILs tracker – Nirmal and Shreyak – 11th September', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:36')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:36'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'PILs tracker – Nirmal and Shreyak – 11th September',
       'NOT_STARTED',
       '2026-09-11',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Shreyak, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'PILs tracker – Nirmal and Shreyak – 11th September',
       'joblist:item:36'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:36' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:36' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:37')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:37'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September',
       'NOT_STARTED',
       '2026-09-11',
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Love, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September',
       'joblist:item:37'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:37' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:37' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Brochure – International and Master – Jaggi (next week)', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:38')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:38'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = 'Jaggi' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Brochure – International and Master – Jaggi (next week)',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'VAGUE_DATE: "next week" is not a date; deadline left NULL | NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Brochure – International and Master – Jaggi (next week)',
       'joblist:item:38'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'PRIMARY'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:38' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description, source_ref)
VALUES ('Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir', NULL, 'Imported verbatim from the 10th Sept job list', 'joblist:job:39')
ON CONFLICT (source_ref) DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE source_ref = 'joblist:job:39'),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1),
     ow AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline, owner_id,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text, source_ref)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM ow),
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Nasir, Nirmal, Nishith — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir',
       'joblist:item:39'
ON CONFLICT (source_ref) DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:39' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:39' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_ref = 'joblist:item:39' AND u.full_name = 'Nishith'
ON CONFLICT DO NOTHING;

COMMIT;
