-- =============================================================================
-- seed.sql — GENERATED by app/scripts/build-seed.mjs. Do not edit by hand.
--
-- Source: Job_list_10th_Sept_3.docx (40 lines, verbatim in
-- app/scripts/source_lines.json). Every row keeps its source_text.
--
-- Nothing here is inferred. Where the document is silent the column is NULL
-- and the row carries needs_review = TRUE. See database/SEED_REVIEW.md for
-- all 76 flags.
--
-- Year assumption: dates in the source omit the year except one. 2026 is
-- taken from line 8 ("Mother & child camp campaign: Vivek 26th Sept 2026") — the only line stating a year.
-- =============================================================================

BEGIN;

-- --- People named in the source ------------------------------------------
-- Placeholder auth ids so the seed can run before real sign-ups exist; when
-- these people register, match on email and re-point the FKs.

INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'akshay@placeholder.invalid', jsonb_build_object('full_name', 'Akshay'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'anshika@placeholder.invalid', jsonb_build_object('full_name', 'Anshika'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'atampreet@placeholder.invalid', jsonb_build_object('full_name', 'Atampreet'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'dr..tarang@placeholder.invalid', jsonb_build_object('full_name', 'Dr. Tarang'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'himanshu@placeholder.invalid', jsonb_build_object('full_name', 'Himanshu'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'jaggi@placeholder.invalid', jsonb_build_object('full_name', 'Jaggi'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'love@placeholder.invalid', jsonb_build_object('full_name', 'Love'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'mudit@placeholder.invalid', jsonb_build_object('full_name', 'Mudit'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'nasir@placeholder.invalid', jsonb_build_object('full_name', 'Nasir'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'nirmal@placeholder.invalid', jsonb_build_object('full_name', 'Nirmal'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'nishith@placeholder.invalid', jsonb_build_object('full_name', 'Nishith'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'parul@placeholder.invalid', jsonb_build_object('full_name', 'Parul'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'shreyak@placeholder.invalid', jsonb_build_object('full_name', 'Shreyak'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'sushant@placeholder.invalid', jsonb_build_object('full_name', 'Sushant'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'vidisha@placeholder.invalid', jsonb_build_object('full_name', 'Vidisha'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'vijaya@placeholder.invalid', jsonb_build_object('full_name', 'Vijaya'))
ON CONFLICT (email) DO NOTHING;
INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (gen_random_uuid(), 'vivek@placeholder.invalid', jsonb_build_object('full_name', 'Vivek'))
ON CONFLICT (email) DO NOTHING;

-- --- Role assignments ------------------------------------------------------
-- NOTE: the source document states NO roles for anyone. These assignments are
-- an ASSUMPTION carried over so RLS is exercisable, flagged as such in the
-- review file. Correct them in the admin UI; nothing in the engine depends on
-- a specific person holding a specific role.
INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, r.id FROM public.users u CROSS JOIN public.roles r
WHERE u.email LIKE '%@placeholder.invalid' AND r.name = 'CREATOR'
ON CONFLICT DO NOTHING;


-- --- Workflow -------------------------------------------------------------
-- A single permissive template so imported rows have somewhere to sit. The
-- real stage list is the 11-stage flow; it is NOT generated here because the
-- source document does not say which stage any item is at.
INSERT INTO public.workflow_templates (name, description, multi_owner_behavior, is_default)
VALUES ('Imported (unclassified)',
        'Holding workflow for rows imported from the 10th Sept job list.',
        'COLLABORATIVE', FALSE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.workflow_stages (workflow_id, name, stage_order, requires_approval)
SELECT w.id, v.name, v.ord, v.appr
FROM public.workflow_templates w,
     (VALUES ('IMPORTED', 1, FALSE), ('APPROVAL', 2, TRUE), ('DONE', 3, FALSE))
       AS v(name, ord, appr)
WHERE w.name = 'Imported (unclassified)'
ON CONFLICT (workflow_id, name) DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'SUBMISSION'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='IMPORTED'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='APPROVAL'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'APPROVED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='DONE'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;

INSERT INTO public.workflow_transitions (workflow_id, from_stage_id, to_stage_id, trigger_condition)
SELECT w.id, s1.id, s2.id, 'CHANGES_REQUIRED'
FROM public.workflow_templates w
JOIN public.workflow_stages s1 ON s1.workflow_id=w.id AND s1.name='APPROVAL'
JOIN public.workflow_stages s2 ON s2.workflow_id=w.id AND s2.name='IMPORTED'
WHERE w.name='Imported (unclassified)'
ON CONFLICT DO NOTHING;


-- --- Jobs and work items ---------------------------------------------------

INSERT INTO public.jobs (name, category, description)
VALUES ('Cardiac : 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Cardiac : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'newspaper ad: hindi & English : Love - closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'newspaper ad: hindi & English : Love - closed';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'newspaper ad: hindi & English : Love - closed' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Cardiac : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Whatsapp : Nasir Closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Whatsapp : Nasir Closed';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Whatsapp : Nasir Closed' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Cardiac : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Emailer : Love - closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Emailer : Love - closed';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Emailer : Love - closed' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Cardiac : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Flyer : Love -',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | NO_STATUS: Line reads "Flyer : Love - " with a trailing dash and nothing after it. Owner is Love; status genuinely absent.',
       'Flyer : Love -';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Flyer : Love -' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Cardiac : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Meta Ad : Closed Nasir',
       'COMPLETED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Meta Ad : Closed Nasir';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Meta Ad : Closed Nasir' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Sales emailer Neuro Fast: love & shreyak : 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Sales emailer Neuro Fast: love & shreyak : 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sales emailer Neuro Fast: love & shreyak : 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Love, Shreyak — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Sales emailer Neuro Fast: love & shreyak : 10th Sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sales emailer Neuro Fast: love & shreyak : 10th Sept' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sales emailer Neuro Fast: love & shreyak : 10th Sept' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('ShardaCare hai na film: anshika : 10th sept by 11 am', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'ShardaCare hai na film: anshika : 10th sept by 11 am' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'ShardaCare hai na film: anshika : 10th sept by 11 am',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'ShardaCare hai na film: anshika : 10th sept by 11 am';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'ShardaCare hai na film: anshika : 10th sept by 11 am' AND u.full_name = 'Anshika'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Mother & child camp campaign: Vivek 26th Sept 2026', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Mother & child camp campaign: Vivek 26th Sept 2026' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'newspaper ad',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'newspaper ad';

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Mother & child camp campaign: Vivek 26th Sept 2026' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Whatsapp',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Whatsapp';

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Mother & child camp campaign: Vivek 26th Sept 2026' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Emailer',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Emailer';

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Mother & child camp campaign: Vivek 26th Sept 2026' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Flyer',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'Flyer';

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Mother & child camp campaign: Vivek 26th Sept 2026' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'P1 Meta creative – 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_OWNER: No owner on this line. Parent "Mother & child camp campaign: Vivek 26th Sept 2026" names Vivek — NOT inherited. | NO_STATUS: No status word in source; left unset',
       'P1 Meta creative – 10th Sept';

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept',
       'NOT_STARTED',
       '2026-09-09',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Himanshu, Dr. Tarang — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | ROLE_AMBIGUOUS: Is "Dr. Tarang" the requester/stakeholder or an owner? The line reads "Dr. Tarang: discuss the requirement" then names Himanshu as doing the video. Recorded as a mention only — no ownership assigned.',
       'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept' AND u.full_name = 'Himanshu'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr. Tarang: discuss the requirement : Walk Through Video – Himanshu – 9th Sept' AND u.full_name = 'Dr. Tarang'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Lab images – Himanshu Vidisha – 10th sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Lab images – Himanshu Vidisha – 10th sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Lab images – Himanshu Vidisha – 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Himanshu, Vidisha — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Lab images – Himanshu Vidisha – 10th sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Lab images – Himanshu Vidisha – 10th sept' AND u.full_name = 'Himanshu'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Lab images – Himanshu Vidisha – 10th sept' AND u.full_name = 'Vidisha'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Physio requirements: read document : Jaggi & Vijaya', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Physio requirements: read document : Jaggi & Vijaya' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Physio requirements: read document : Jaggi & Vijaya',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Jaggi, Vijaya — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Physio requirements: read document : Jaggi & Vijaya';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Physio requirements: read document : Jaggi & Vijaya' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Physio requirements: read document : Jaggi & Vijaya' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('World heart day newspaper ad (half advertorial half ad) content - Vijaya', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'World heart day newspaper ad (half advertorial half ad) content - Vijaya' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'World heart day newspaper ad (half advertorial half ad) content - Vijaya',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'World heart day newspaper ad (half advertorial half ad) content - Vijaya';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'World heart day newspaper ad (half advertorial half ad) content - Vijaya' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Shreyak, Nirmal, Mudit — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'NABH Signages: Nirmal/Mudit/ Shreyak – 10th Sept' AND u.full_name = 'Mudit'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Atampreet' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing',
       'PENDING',
       NULL,
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Vijaya, Atampreet — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | ROLE_AMBIGUOUS: "get it approved by atampreet" makes Atampreet the APPROVER, not the owner. "Vijaya for makerchecker" is a second, different review role. The line also ends "sent for printing", implying it already passed both. Sequence not reconstructible from the source. | UNPARSED_TERM: "total solutions" — unclear whether a vendor name, a deliverable, or part of the booklet title.',
       'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Stroke booklet: release; get it approved by atampreet: total solutions  : Vijaya for makerchecker – sent for printing' AND u.full_name = 'Atampreet'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Akshay' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)',
       'PENDING',
       '2026-09-08',
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'MULTIPLE_PEOPLE: Vivek, Vijaya, Akshay — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)' AND u.full_name = 'Vivek'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)' AND u.full_name = 'Vijaya'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Maxwell brochure : Vivek   & Vijaya 8th Sept – sent to Akshay for approval (on 9th)' AND u.full_name = 'Akshay'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS',
       'PENDING',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Nasir, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | UNRESOLVED_RECIPIENT: Cannot resolve "ms" to a person | UNRESOLVED_RECIPIENT: "MS" is an unresolved initialism (Medical Superintendent?). Not added to the roster; recorded verbatim.',
       'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'KTP now available at sharda hospital: gate 1 hoarding: Nasir – sent to nirmal and MS' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('PIL IUI: Jaggi : 12th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'PIL IUI: Jaggi : 12th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'PIL IUI: Jaggi : 12th Sept',
       'NOT_STARTED',
       '2026-09-12',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'PIL IUI: Jaggi : 12th Sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'PIL IUI: Jaggi : 12th Sept' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed',
       'COMPLETED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       FALSE,
       NULL,
       'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sandwich posters: Pulmonary, Gastro, nephro: Jaggi : 10th Sept: Closed' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='APPROVAL'),
     pw AS (SELECT id FROM public.users WHERE full_name = 'Parul' LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th',
       'PENDING',
       NULL,
       (SELECT id FROM pw),
       NULL,
       TRUE,
       'PENDING',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | MULTIPLE_PEOPLE: Jaggi, Parul — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | PENDING_WITH_NAMED: Source says "approval pending" AND names Parul. Per your instruction the named person wins, so pending_with = Parul rather than the literal "unknown".',
       'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Wall of fame: Jaggi – options shared wth Parul ma’am, approval pending – 9th' AND u.full_name = 'Parul'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Green belt design approval and costing : costing sent to purchase 9th Sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Green belt design approval and costing : costing sent to purchase 9th Sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Green belt design approval and costing : costing sent to purchase 9th Sept',
       'PENDING',
       '2026-09-09',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_OWNER: No owner named anywhere on this line; owner left NULL | UNRESOLVED_RECIPIENT: Cannot resolve "purchase 9th sept" to a person',
       'Green belt design approval and costing : costing sent to purchase 9th Sept';

INSERT INTO public.jobs (name, category, description)
VALUES ('Roundabout creatives: flagpoles: Jaggi:  10th sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Roundabout creatives: flagpoles: Jaggi:  10th sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Roundabout creatives: flagpoles: Jaggi:  10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Roundabout creatives: flagpoles: Jaggi:  10th sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Roundabout creatives: flagpoles: Jaggi:  10th sept' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('YK sir Grandson video : Anshika & Vidisha – 9th sept closed10', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10',
       'COMPLETED',
       '2026-09-09',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'MULTIPLE_PEOPLE: Anshika, Vidisha — all kept as collaborators. Which (if any) is the single accountable owner is not stated. | SOURCE_ARTEFACT: Line ends "closed10" — the trailing "10" appears to be a stray list number, not part of the status. Read as "closed"; the "10" is discarded but preserved in source_text.',
       'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10' AND u.full_name = 'Anshika'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'YK sir Grandson video : Anshika & Vidisha – 9th sept closed10' AND u.full_name = 'Vidisha'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Nasir, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Ayushman Bharat Branding Sharda Hospital : Nasir and Nirmal 10th sept' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Printing Collateral Ayushman Event – Nasir : closed', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Printing Collateral Ayushman Event – Nasir : closed' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Printing Collateral Ayushman Event – Nasir : closed',
       'COMPLETED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Printing Collateral Ayushman Event – Nasir : closed';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Printing Collateral Ayushman Event – Nasir : closed' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr. Lipi Clinic branding – Nirmal – vendor aligned', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr. Lipi Clinic branding – Nirmal – vendor aligned' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Lipi Clinic branding – Nirmal – vendor aligned',
       'IN_PROGRESS',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL',
       'Dr. Lipi Clinic branding – Nirmal – vendor aligned';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr. Lipi Clinic branding – Nirmal – vendor aligned' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr. Ruchi & Dr. Ravindra Clinic Branding- Nirmal – 10th sept' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr Avinash clinic branding – 10th sept Shreyak', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr Avinash clinic branding – 10th sept Shreyak' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr Avinash clinic branding – 10th sept Shreyak',
       'NOT_STARTED',
       '2026-09-10',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset',
       'Dr Avinash clinic branding – 10th sept Shreyak';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr Avinash clinic branding – 10th sept Shreyak' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)',
       'PENDING',
       '2026-09-11',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'DATE_MEANING: "vendor aligned for 11th sept" — the 11th Sept refers to the vendor visit, not necessarily the work deadline. Recorded as deadline with this caveat.',
       'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr. Vivek Yadav Clinic Branding- Nirmal (recce pending – vendor aligned for 11th sept)' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dibrugarh Flyer - Vivek', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dibrugarh Flyer - Vivek' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dibrugarh Flyer - Vivek',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Dibrugarh Flyer - Vivek';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dibrugarh Flyer - Vivek' AND u.full_name = 'Vivek'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Outstation Hoarding  - Sushant', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Outstation Hoarding  - Sushant' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Outstation Hoarding  - Sushant',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Outstation Hoarding  - Sushant';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Outstation Hoarding  - Sushant' AND u.full_name = 'Sushant'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('PILs tracker – Nirmal and Shreyak – 11th September', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'PILs tracker – Nirmal and Shreyak – 11th September' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'PILs tracker – Nirmal and Shreyak – 11th September',
       'NOT_STARTED',
       '2026-09-11',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Shreyak, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'PILs tracker – Nirmal and Shreyak – 11th September';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'PILs tracker – Nirmal and Shreyak – 11th September' AND u.full_name = 'Shreyak'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'PILs tracker – Nirmal and Shreyak – 11th September' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September',
       'NOT_STARTED',
       '2026-09-11',
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Love, Nirmal — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September' AND u.full_name = 'Love'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Dr Pallav Mishra printing collaterals – Love and Nirmal – 11th September' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Brochure – International and Master – Jaggi (next week)', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Brochure – International and Master – Jaggi (next week)' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Brochure – International and Master – Jaggi (next week)',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'VAGUE_DATE: "next week" is not a date; deadline left NULL | NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset',
       'Brochure – International and Master – Jaggi (next week)';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Brochure – International and Master – Jaggi (next week)' AND u.full_name = 'Jaggi'
ON CONFLICT DO NOTHING;

INSERT INTO public.jobs (name, category, description)
VALUES ('Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir', NULL, 'Imported verbatim from the 10th Sept job list')
ON CONFLICT DO NOTHING;

WITH j AS (SELECT id FROM public.jobs WHERE name = 'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir' LIMIT 1),
     w AS (SELECT id FROM public.workflow_templates WHERE name='Imported (unclassified)'),
     s AS (SELECT id FROM public.workflow_stages
           WHERE workflow_id=(SELECT id FROM w) AND name='IMPORTED'),
     pw AS (SELECT id FROM public.users WHERE full_name = NULL LIMIT 1)
INSERT INTO public.work_items
  (job_id, workflow_id, current_stage_id, name, status, deadline,
   pending_with_id, pending_with_label, approval_required, approval_status,
   needs_review, review_notes, source_text)
SELECT (SELECT id FROM j), (SELECT id FROM w), (SELECT id FROM s),
       'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir',
       'NOT_STARTED',
       NULL,
       (SELECT id FROM pw),
       NULL,
       FALSE,
       'NOT_REQUIRED',
       TRUE,
       'NO_DEADLINE: No date in source; deadline left NULL | NO_STATUS: No status word in source; left unset | MULTIPLE_PEOPLE: Nasir, Nirmal, Nishith — all kept as collaborators. Which (if any) is the single accountable owner is not stated.',
       'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir';

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir' AND u.full_name = 'Nasir'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir' AND u.full_name = 'Nirmal'
ON CONFLICT DO NOTHING;

INSERT INTO public.work_item_owners (work_item_id, user_id, owner_role)
SELECT wi.id, u.id, 'COLLABORATOR'
FROM public.work_items wi, public.users u
WHERE wi.source_text = 'Sepsis Week (Banners , digital standees, selfie booth, emailer) – Nishith, Nirmal & Nasir' AND u.full_name = 'Nishith'
ON CONFLICT DO NOTHING;

COMMIT;
